In [3]:
import pandas as pd
df=pd.read_excel("ApexPlanet_DataAnalytics_Dataset.xlsx")
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            980 non-null    float64
 5   Gender         1000 non-null   object
 6   City           987 non-null    object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB

In [5]:
df.columns.tolist()

['Order_ID',
 'Order_Date',
 'Customer_ID',
 'Customer_Name',
 'Age',
 'Gender',
 'City',
 'Product',
 'Category',
 'Quantity',
 'Unit_Price',
 'Total_Sales']

In [6]:
df.dtypes

Order_ID          object
Order_Date        object
Customer_ID       object
Customer_Name     object
Age              float64
Gender            object
City              object
Product           object
Category          object
Quantity           int64
Unit_Price       float64
Total_Sales      float64
dtype: object

In [7]:
data_dictionary = pd.DataFrame({
    "Column Name" : df.columns,
    "Data Type" : 
df.dtypes.astype(str),
    "Missing Values" :
df.isnull().sum(),
    "Unique Values" : df.nunique()
})

data_dictionary

                 Column Name Data Type  Missing Values  Unique Values
Order_ID            Order_ID    object               0            992
Order_Date        Order_Date    object               0            342
Customer_ID      Customer_ID    object               0            947
Customer_Name  Customer_Name    object               0            425
Age                      Age   float64              20             48
Gender                Gender    object               0              2
City                    City    object              13              8
Product              Product    object               0              6
Category            Category    object               0              5
Quantity            Quantity     int64               0             10
Unit_Price        Unit_Price   float64               0           1000
Total_Sales      Total_Sales   float64               0           1000

In [8]:
data_dictionary["Meaning"] = [
    "Unique identifier for each order",
    "Date when the order was placed",
    "Name of the customer",
    "Age of the customer",
    "City of the customer",
    "Product purchased",
    "Category of the product",
    "Quantity of products purchased",
    "Price of one unit",
    "Total sales/revenue generated",
    "Payment method used",
    "Sales region"
]

data_dictionary["Business Use"] = [
    "Identify and track individual orders",
    "Analyze sales trends over time",
    "Understand customer purchasing behavior",
    "Analyze customer demographics",
    "Perform city-wise sales analysis",
    "Identify product-level sales performance",
    "Compare performance across product categories",
    "Analyze quantity and sales volume",
    "Calculate and analyze revenue",
    "Measure total revenue and sales performance",
    "Analyze customer payment preferences",
    "Compare sales performance across regions"
]

data_dictionary

,Column Name,Data Type,Missing Values,Unique Values,Meaning,Business Use
Order_ID,Order_ID,object,0,992,Unique identifier for each order,Identify and track individual orders
Order_Date,Order_Date,object,0,342,Date when the order was placed,Analyze sales trends over time
Customer_ID,Customer_ID,object,0,947,Name of the customer,Understand customer purchasing behavior
Customer_Name,Customer_Name,object,0,425,Age of the customer,Analyze customer demographics
Age,Age,float64,20,48,City of the customer,Perform city-wise sales analysis
Gender,Gender,object,0,2,Product purchased,Identify product-level sales performance
City,City,object,13,8,Category of the product,Compare performance across product categories
Product,Product,object,0,6,Quantity of products purchased,Analyze quantity and sales volume
Category,Category,object,0,5,Price of one unit,Calculate and analyze revenue
Quantity,Quantity,int64,0,10,Total sales/revenue generated,Measure total revenue and sales performance
Unit_Price,Unit_Price,float64,0,1000,Payment method used,Analyze customer payment preferences
Total_Sales,Total_Sales,float64,0,1000,Sales region,Compare sales performance across regions

In [9]:
data_dictionary.to_excel("data_dictionary.xlsx", index=False)
print("Data Dictionary Saved Successfully!")

Data Dictionary Saved Successfully!

In [12]:
missing_values = df.isnull().sum()

missing_values

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

In [15]:
duplicate_rows = df.duplicated().sum()

print("Total duplicates rows:" , duplicate_rows)

Total duplicates rows: 0

In [16]:
duplicate_order_ids = df[df["Order_ID"].duplicated(keep=False)]
duplicate_order_ids

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
48,ORD100050,2025-10-03,CUST5523,Customer_432,NaN,Male,Pune,Chair,Furniture,9,30834.87,277513.83
118,ORD100050,2025-01-22,CUST3194,Customer_114,34.0,Male,Kolkata,Book,Education,2,25795.55,51591.10
238,ORD100050,2025-03-01,CUST8467,Customer_104,23.0,Male,Bengaluru,Book,Education,3,2860.83,8582.49
358,ORD100050,2025-02-11,CUST6467,Customer_181,24.0,Female,Pune,Rice,Grocery,7,45480.39,318362.73
478,ORD100050,2025-11-22,CUST8225,Customer_468,64.0,Male,Bengaluru,Rice,Grocery,8,38957.59,311660.72
598,ORD100050,2025-02-21,CUST8859,Customer_53,NaN,Male,NaN,Laptop,Electronics,7,20144.84,141013.88
718,ORD100050,2025-11-06,CUST7824,Customer_190,31.0,Female,Mumbai,Rice,Grocery,4,42642.59,170570.36
838,ORD100050,2025-08-03,CUST5585,Customer_289,35.0,Male,Kolkata,Chair,Furniture,9,28747.47,258727.23
958,ORD100050,2025-02-09,CUST7188,Customer_89,62.0,Male,Bengaluru,Mobile,Electronics,1,34619.77,34619.77

In [18]:
duplicate_order_ids.sort_values("Order_ID")

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
48,ORD100050,2025-10-03,CUST5523,Customer_432,NaN,Male,Pune,Chair,Furniture,9,30834.87,277513.83
118,ORD100050,2025-01-22,CUST3194,Customer_114,34.0,Male,Kolkata,Book,Education,2,25795.55,51591.10
238,ORD100050,2025-03-01,CUST8467,Customer_104,23.0,Male,Bengaluru,Book,Education,3,2860.83,8582.49
358,ORD100050,2025-02-11,CUST6467,Customer_181,24.0,Female,Pune,Rice,Grocery,7,45480.39,318362.73
478,ORD100050,2025-11-22,CUST8225,Customer_468,64.0,Male,Bengaluru,Rice,Grocery,8,38957.59,311660.72
598,ORD100050,2025-02-21,CUST8859,Customer_53,NaN,Male,NaN,Laptop,Electronics,7,20144.84,141013.88
718,ORD100050,2025-11-06,CUST7824,Customer_190,31.0,Female,Mumbai,Rice,Grocery,4,42642.59,170570.36
838,ORD100050,2025-08-03,CUST5585,Customer_289,35.0,Male,Kolkata,Chair,Furniture,9,28747.47,258727.23
958,ORD100050,2025-02-09,CUST7188,Customer_89,62.0,Male,Bengaluru,Mobile,Electronics,1,34619.77,34619.77

In [20]:
duplicate_order_ids.groupby("Order_ID").size()

Order_ID
ORD100050    9
dtype: int64

In [21]:
df[df["Age"].isnull()]

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
48,ORD100050,2025-10-03,CUST5523,Customer_432,NaN,Male,Pune,Chair,Furniture,9,30834.87,277513.83
98,ORD100100,2025-11-02,CUST7462,Customer_379,NaN,Male,Patna,Laptop,Electronics,5,553.62,2768.10
148,ORD100150,2025-04-01,CUST4132,Customer_47,NaN,Female,NaN,Chair,Furniture,4,1973.64,7894.56
198,ORD100200,2025-02-24,CUST2953,Customer_435,NaN,Female,Kolkata,Rice,Grocery,8,27608.55,220868.40
248,ORD100250,2025-12-20,CUST3169,Customer_138,NaN,Female,Delhi,Mobile,Electronics,7,19829.73,138808.11
298,ORD100300,2025-07-01,CUST7944,Customer_282,NaN,Male,NaN,Chair,Furniture,6,28595.31,171571.86
348,ORD100350,2025-07-11,CUST9709,Customer_409,NaN,Male,Pune,Laptop,Electronics,8,47254.70,378037.60
398,ORD100400,2025-04-20,CUST5102,Customer_416,NaN,Female,Hyderabad,Book,Education,3,26269.62,78808.86
448,ORD100450,2025-02-13,CUST6714,Customer_31,NaN,Female,NaN,Book,Education,10,43946.96,439469.60
498,ORD100500,2025-06-26,CUST2835,Customer_468,NaN,Male,Kolkata,Chair,Furniture,9,7268.14,65413.26
548,ORD100550,2025-03-27,CUST5244,Customer_44,NaN,Male,Pune,Rice,Grocery,5,41509.54,207547.70
598,ORD100050,2025-02-21,CUST8859,Customer_53,NaN,Male,NaN,Laptop,Electronics,7,20144.84,141013.88
648,ORD100650,2025-09-22,CUST2181,Customer_125,NaN,Female,Bengaluru,Rice,Grocery,3,7467.04,22401.12
698,ORD100700,2025-05-20,CUST9674,Customer_232,NaN,Female,Mumbai,Mobile,Electronics,9,11808.33,106274.97
748,ORD100750,2025-07-18,CUST3730,Customer_273,NaN,Female,NaN,Chair,Furniture,10,43808.06,438080.60
798,ORD100800,2025-09-27,CUST1618,Customer_166,NaN,Male,Patna,Rice,Grocery,10,15891.66,158916.60
848,ORD100850,2025-04-12,CUST2834,Customer_98,NaN,Male,Kolkata,Rice,Grocery,9,30091.26,270821.34
898,ORD100900,2025-04-27,CUST3867,Customer_54,NaN,Female,NaN,Laptop,Electronics,5,5069.79,25348.95
948,ORD100950,2025-11-01,CUST6316,Customer_59,NaN,Male,Pune,Laptop,Electronics,9,34569.56,311126.04
998,ORD101000,2025-02-21,CUST9501,Customer_241,NaN,Male,Delhi,Mobile,Electronics,9,2879.01,25911.09

In [23]:
df["Age"].describe()

count    980.000000
mean      41.360204
std       13.822597
min       18.000000
25%       30.000000
50%       41.000000
75%       54.000000
max       65.000000
Name: Age, dtype: float64

In [24]:
median_age = df["Age"].median()

print("Median Age:" , median_age)

Median Age: 41.0

In [25]:
df["Age"] = df["Age"].fillna(median_age)

print("Missing Age values:" , df["Age"].isnull().sum())

Missing Age values: 0

In [26]:
df[df["City"].isnull()]

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
73,ORD100075,2025-03-30,CUST2157,Customer_31,58.0,Male,NaN,Mobile,Electronics,4,21599.26,86397.04
148,ORD100150,2025-04-01,CUST4132,Customer_47,41.0,Female,NaN,Chair,Furniture,4,1973.64,7894.56
223,ORD100225,2025-12-07,CUST1443,Customer_315,37.0,Female,NaN,Rice,Grocery,1,25336.70,25336.70
298,ORD100300,2025-07-01,CUST7944,Customer_282,41.0,Male,NaN,Chair,Furniture,6,28595.31,171571.86
373,ORD100375,2025-05-06,CUST5835,Customer_362,20.0,Male,NaN,Laptop,Electronics,2,28311.58,56623.16
448,ORD100450,2025-02-13,CUST6714,Customer_31,41.0,Female,NaN,Book,Education,10,43946.96,439469.60
523,ORD100525,2025-12-31,CUST1090,Customer_316,45.0,Female,NaN,Shoes,Fashion,7,751.97,5263.79
598,ORD100050,2025-02-21,CUST8859,Customer_53,41.0,Male,NaN,Laptop,Electronics,7,20144.84,141013.88
673,ORD100675,2025-11-20,CUST8502,Customer_220,47.0,Male,NaN,Laptop,Electronics,1,14756.18,14756.18
748,ORD100750,2025-07-18,CUST3730,Customer_273,41.0,Female,NaN,Chair,Furniture,10,43808.06,438080.60
823,ORD100825,2025-07-13,CUST9718,Customer_11,57.0,Female,NaN,Laptop,Electronics,2,45863.13,91726.26
898,ORD100900,2025-04-27,CUST3867,Customer_54,41.0,Female,NaN,Laptop,Electronics,5,5069.79,25348.95
973,ORD100975,2025-10-15,CUST2870,Customer_311,25.0,Female,NaN,Book,Education,6,6189.16,37134.96

In [28]:
df["City"].value_counts()

City
Patna        135
Kolkata      133
Mumbai       131
Hyderabad    125
Delhi        125
Bengaluru    122
Gaya         117
Pune          99
Name: count, dtype: int64

In [29]:
city_mode = df["City"].mode()[0]

print("Most common city:", city_mode)

df["City"] = df["City"].fillna(city_mode)

print("Missing City values:", df["City"].isnull().sum())

Most common city: Patna
Missing City values: 0

In [31]:
df["Order_Date"].dtype

dtype('O')

In [34]:
df["Order_Date"] =  pd.to_datetime(df["Order_Date"])

print(df["Order_Date"].dtype)

datetime64[ns]

In [35]:
df.describe()

,Order_Date,Age,Quantity,Unit_Price,Total_Sales
count,1000,1000.000000,1000.000000,1000.000000,1000.000000
mean,2025-07-03 11:19:40.800000,41.353000,5.435000,25486.783410,139399.439650
min,2025-01-01 00:00:00,18.000000,1.000000,145.780000,437.340000
25%,2025-03-30 18:00:00,30.000000,3.000000,13895.722500,47066.632500
50%,2025-07-01 00:00:00,41.000000,5.000000,25398.740000,108594.025000
75%,2025-10-07 06:00:00,53.000000,8.000000,37512.382500,203722.882500
max,2026-01-01 00:00:00,65.000000,10.000000,49997.530000,493677.500000
std,NaN,13.683626,2.838632,14179.402361,114100.051546

In [36]:
Q1 = df["Age"].quantile(0.25)
Q3 = df["Age"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers_age = df[
    (df["Age"] < lower_limit) |
    (df["Age"] > upper_limit)
]

print("Lower limit:", lower_limit)
print("Upper limit:", upper_limit)
print("Age outliers:", len(outliers_age))

Lower limit: -4.5
Upper limit: 87.5
Age outliers: 0

In [37]:
Q1 = df["Quantity"].quantile(0.25)
Q3 = df["Quantity"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers_quantity = df[
    (df["Quantity"] < lower_limit) |
    (df["Quantity"] > upper_limit)
]

print("Lower limit:", lower_limit)
print("Upper limit:", upper_limit)
print("Quantity outliers:", len(outliers_quantity))

Lower limit: -4.5
Upper limit: 15.5
Quantity outliers: 0

In [38]:
Q1 = df["Unit_Price"].quantile(0.25)
Q3 = df["Unit_Price"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers_price = df[
    (df["Unit_Price"] < lower_limit) |
    (df["Unit_Price"] > upper_limit)
]

print("Lower limit:", lower_limit)
print("Upper limit:", upper_limit)
print("Unit Price outliers:", len(outliers_price))

Lower limit: -21529.267499999998
Upper limit: 72937.3725
Unit Price outliers: 0

In [41]:
Q1 = df["Total_Sales"].quantile(0.25)
Q3 = df["Total_Sales"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers_sales = df[
    (df["Total_Sales"] < lower_limit) |
    (df["Total_Sales"] > upper_limit)
]

print("Lower limit:", lower_limit)
print("Upper limit:", upper_limit)
print("Total_Sales outliers:", len(outliers_sales))

Lower limit: -187917.7425
Upper limit: 438707.2575
Total_Sales outliers: 19

In [43]:
outliers_total_sales = df[
    (df["Total_Sales"] < lower_limit) |
    (df["Total_Sales"] > upper_limit)
]

outliers_total_sales[["Order_ID", "Order_Date", "Product", "Quantity", "Unit_Price", "Total_Sales"]]

      Order_ID Order_Date Product  Quantity  Unit_Price  Total_Sales
50   ORD100052 2025-09-09    Book        10    49367.75    493677.50
81   ORD100083 2025-01-06  Laptop         9    48845.50    439609.50
150  ORD100152 2025-02-08  Laptop         9    48833.27    439499.43
173  ORD100175 2025-06-07    Rice         9    49390.42    444513.78
220  ORD100222 2025-07-13   Shoes        10    49086.64    490866.40
364  ORD100366 2025-03-13  Mobile        10    47493.59    474935.90
396  ORD100398 2025-03-07  Mobile         9    48807.37    439266.33
432  ORD100434 2025-06-10  Mobile        10    43997.22    439972.20
448  ORD100450 2025-02-13    Book        10    43946.96    439469.60
462  ORD100464 2025-09-17    Book        10    44045.66    440456.60
622  ORD100624 2025-06-21    Rice        10    48255.19    482551.90
656  ORD100658 2025-10-14   Shoes        10    46270.13    462701.30
691  ORD100693 2025-12-09    Book        10    45877.49    458774.90
712  ORD100714 2025-05-05  Mobile        10    47079.86    470798.60
721  ORD100723 2025-11-28  Laptop        10    44401.64    444016.40
762  ORD100764 2025-10-13  Laptop        10    49217.41    492174.10
947  ORD100949 2025-05-17    Book        10    47314.42    473144.20
972  ORD100974 2025-07-28  Laptop        10    48566.78    485667.80
980  ORD100982 2025-03-30    Rice        10    46852.20    468522.00

In [44]:
df["Calculated Sales"] = df["Quantity"] * df["Unit_Price"]

print((df["Total_Sales"] == df["Calculated Sales"]).all())

False

In [45]:
mismatch = df[
    df["Total_Sales"] != df["Calculated Sales"]
]

print("Mismatched rows:", len(mismatch))

Mismatched rows: 178

In [46]:
Q1 = df["Total_Sales"].quantile(0.25)
Q3 = df["Total_Sales"].quantile(0.75)

IQR = Q3 - Q1

lower_sales = Q1 - 1.5 * IQR
upper_sales = Q3 + 1.5 * IQR

print("Lower limit:", lower_sales)
print("Upper limit:", upper_sales)

Lower limit: -187917.7425
Upper limit: 438707.2575

In [47]:
sales_outliers = df[
    (df["Total_Sales"] < lower_sales) |
    (df["Total_Sales"] > upper_sales)
]

print("Total_Sales outliers:", len(sales_outliers))

Total_Sales outliers: 19

In [48]:
sales_outliers[[
    "Order_ID",
    "Quantity",
    "Unit_Price",
    "Total_Sales"
]]

      Order_ID  Quantity  Unit_Price  Total_Sales
50   ORD100052        10    49367.75    493677.50
81   ORD100083         9    48845.50    439609.50
150  ORD100152         9    48833.27    439499.43
173  ORD100175         9    49390.42    444513.78
220  ORD100222        10    49086.64    490866.40
364  ORD100366        10    47493.59    474935.90
396  ORD100398         9    48807.37    439266.33
432  ORD100434        10    43997.22    439972.20
448  ORD100450        10    43946.96    439469.60
462  ORD100464        10    44045.66    440456.60
622  ORD100624        10    48255.19    482551.90
656  ORD100658        10    46270.13    462701.30
691  ORD100693        10    45877.49    458774.90
712  ORD100714        10    47079.86    470798.60
721  ORD100723        10    44401.64    444016.40
762  ORD100764        10    49217.41    492174.10
947  ORD100949        10    47314.42    473144.20
972  ORD100974        10    48566.78    485667.80
980  ORD100982        10    46852.20    468522.00

In [49]:
sales_outliers["Calculated_Sales"] = (
    sales_outliers["Quantity"] * sales_outliers["Unit_Price"]
)

sales_outliers[[
    "Order_ID",
    "Quantity",
    "Unit_Price",
    "Total_Sales",
    "Calculated_Sales"
]]

C:\Users\ASUS\AppData\Local\Temp\ipykernel_21360\1445145478.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_outliers["Calculated_Sales"] = (

      Order_ID  Quantity  Unit_Price  Total_Sales  Calculated_Sales
50   ORD100052        10    49367.75    493677.50         493677.50
81   ORD100083         9    48845.50    439609.50         439609.50
150  ORD100152         9    48833.27    439499.43         439499.43
173  ORD100175         9    49390.42    444513.78         444513.78
220  ORD100222        10    49086.64    490866.40         490866.40
364  ORD100366        10    47493.59    474935.90         474935.90
396  ORD100398         9    48807.37    439266.33         439266.33
432  ORD100434        10    43997.22    439972.20         439972.20
448  ORD100450        10    43946.96    439469.60         439469.60
462  ORD100464        10    44045.66    440456.60         440456.60
622  ORD100624        10    48255.19    482551.90         482551.90
656  ORD100658        10    46270.13    462701.30         462701.30
691  ORD100693        10    45877.49    458774.90         458774.90
712  ORD100714        10    47079.86    470798.60         470798.60
721  ORD100723        10    44401.64    444016.40         444016.40
762  ORD100764        10    49217.41    492174.10         492174.10
947  ORD100949        10    47314.42    473144.20         473144.20
972  ORD100974        10    48566.78    485667.80         485667.80
980  ORD100982        10    46852.20    468522.00         468522.00

In [52]:
sales_outliers["Calculated_Sales"] = (sales_outliers["Quantity"] * sales_outliers["Unit_Price"])

sales_outliers[[
    "Order_ID",
    "Quantity",
    "Unit_Price",
    "Total_Sales",
    "Calculated_Sales"
]]

C:\Users\ASUS\AppData\Local\Temp\ipykernel_21360\1247736674.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_outliers["Calculated_Sales"] = (sales_outliers["Quantity"] * sales_outliers["Unit_Price"])

      Order_ID  Quantity  Unit_Price  Total_Sales  Calculated_Sales
50   ORD100052        10    49367.75    493677.50         493677.50
81   ORD100083         9    48845.50    439609.50         439609.50
150  ORD100152         9    48833.27    439499.43         439499.43
173  ORD100175         9    49390.42    444513.78         444513.78
220  ORD100222        10    49086.64    490866.40         490866.40
364  ORD100366        10    47493.59    474935.90         474935.90
396  ORD100398         9    48807.37    439266.33         439266.33
432  ORD100434        10    43997.22    439972.20         439972.20
448  ORD100450        10    43946.96    439469.60         439469.60
462  ORD100464        10    44045.66    440456.60         440456.60
622  ORD100624        10    48255.19    482551.90         482551.90
656  ORD100658        10    46270.13    462701.30         462701.30
691  ORD100693        10    45877.49    458774.90         458774.90
712  ORD100714        10    47079.86    470798.60         470798.60
721  ORD100723        10    44401.64    444016.40         444016.40
762  ORD100764        10    49217.41    492174.10         492174.10
947  ORD100949        10    47314.42    473144.20         473144.20
972  ORD100974        10    48566.78    485667.80         485667.80
980  ORD100982        10    46852.20    468522.00         468522.00

In [53]:
sales_outliers["Sales_Check"] = (
    sales_outliers["Total_Sales"].round(2) ==
    sales_outliers["Calculated_Sales"].round(2)
)

print(sales_outliers["Sales_Check"].value_counts())

Sales_Check
True    19
Name: count, dtype: int64

C:\Users\ASUS\AppData\Local\Temp\ipykernel_21360\2814907901.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_outliers["Sales_Check"] = (

In [54]:
df.drop(columns=["Calculated_Sales"], inplace=True, errors="ignore")

print(df.columns.tolist())

['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age', 'Gender', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price', 'Total_Sales', 'Calculated Sales']

In [55]:
duplicate_orders = df[df["Order_ID"].duplicated(keep=False)].sort_values("Order_ID")

duplicate_orders

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales,Calculated Sales
48,ORD100050,2025-10-03,CUST5523,Customer_432,41.0,Male,Pune,Chair,Furniture,9,30834.87,277513.83,277513.83
118,ORD100050,2025-01-22,CUST3194,Customer_114,34.0,Male,Kolkata,Book,Education,2,25795.55,51591.10,51591.10
238,ORD100050,2025-03-01,CUST8467,Customer_104,23.0,Male,Bengaluru,Book,Education,3,2860.83,8582.49,8582.49
358,ORD100050,2025-02-11,CUST6467,Customer_181,24.0,Female,Pune,Rice,Grocery,7,45480.39,318362.73,318362.73
478,ORD100050,2025-11-22,CUST8225,Customer_468,64.0,Male,Bengaluru,Rice,Grocery,8,38957.59,311660.72,311660.72
598,ORD100050,2025-02-21,CUST8859,Customer_53,41.0,Male,Patna,Laptop,Electronics,7,20144.84,141013.88,141013.88
718,ORD100050,2025-11-06,CUST7824,Customer_190,31.0,Female,Mumbai,Rice,Grocery,4,42642.59,170570.36,170570.36
838,ORD100050,2025-08-03,CUST5585,Customer_289,35.0,Male,Kolkata,Chair,Furniture,9,28747.47,258727.23,258727.23
958,ORD100050,2025-02-09,CUST7188,Customer_89,62.0,Male,Bengaluru,Mobile,Electronics,1,34619.77,34619.77,34619.77

In [56]:
id_check = duplicate_orders.groupby("Order_ID").agg({
    "Customer_Name": "nunique",
    "Product": "nunique",
    "Quantity": "nunique",
    "Unit_Price": "nunique",
    "Total_Sales": "nunique"
})

id_check

           Customer_Name  Product  Quantity  Unit_Price  Total_Sales
Order_ID
ORD100050              9        5         7           9            9

In [57]:
print("Exact duplicate rows:", df.duplicated().sum())

Exact duplicate rows: 0

In [58]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_ID         0
Customer_Name       0
Age                 0
Gender              0
City                0
Product             0
Category            0
Quantity            0
Unit_Price          0
Total_Sales         0
Calculated Sales    0
dtype: int64

In [59]:
quality_summary = pd.DataFrame({
    "Check": [
        "Total Rows",
        "Total Columns",
        "Missing Values",
        "Exact Duplicate Rows",
        "Duplicate Order IDs",
        "Age Outliers",
        "Quantity Outliers",
        "Unit Price Outliers",
        "Total Sales Outliers"
    ],
    "Result": [
        len(df),
        len(df.columns),
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        df["Order_ID"].duplicated().sum(),
        len(df[(df["Age"] < -4.5) | (df["Age"] > 87.5)]),
        0,
        0,
        len(sales_outliers)
    ]
})

quality_summary

                  Check  Result
0            Total Rows    1000
1         Total Columns      13
2        Missing Values       0
3  Exact Duplicate Rows       0
4   Duplicate Order IDs       8
5          Age Outliers       0
6     Quantity Outliers       0
7   Unit Price Outliers       0
8  Total Sales Outliers      19

In [60]:
print(df.dtypes)

Order_ID                    object
Order_Date          datetime64[ns]
Customer_ID                 object
Customer_Name               object
Age                        float64
Gender                      object
City                        object
Product                     object
Category                    object
Quantity                     int64
Unit_Price                 float64
Total_Sales                float64
Calculated Sales           float64
dtype: object

In [61]:
df.to_csv("cleaned_sales_dataset.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [62]:
check_df = pd.read_csv("cleaned_sales_dataset.csv")

print("Rows:", check_df.shape[0])
print("Columns:", check_df.shape[1])
print("\nMissing values:")
print(check_df.isnull().sum())

Rows: 1000
Columns: 13

Missing values:
Order_ID            0
Order_Date          0
Customer_ID         0
Customer_Name       0
Age                 0
Gender              0
City                0
Product             0
Category            0
Quantity            0
Unit_Price          0
Total_Sales         0
Calculated Sales    0
dtype: int64

In [63]:
print(check_df.columns.tolist())

['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age', 'Gender', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price', 'Total_Sales', 'Calculated Sales']

In [67]:
df.drop(columns=["Calculated Sales"], inplace=True)

print("Calculated Sales column removed!")
print("Total columns:", df.shape[1])

Calculated Sales column removed!
Total columns: 12

In [68]:
df.to_csv("cleaned_sales_dataset.csv", index=False)

print("Final cleaned dataset saved!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Final cleaned dataset saved!
Rows: 1000
Columns: 12

In [69]:
quality_summary.to_excel("data_quality_summary.xlsx", index=False)

print("Data quality summary saved successfully!")

Data quality summary saved successfully!

In [70]:
data_dictionary = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str).values,
    "Description": [
        "Unique identifier for each order",
        "Date when the order was placed",
        "Unique identifier of the customer",
        "Name of the customer",
        "Age of the customer",
        "Gender of the customer",
        "City where the customer is located",
        "Name of the purchased product",
        "Category of the purchased product",
        "Number of units purchased",
        "Price per unit",
        "Total sales amount for the order"
    ]
})

data_dictionary

           Column       Data Type                         Description
0        Order_ID          object    Unique identifier for each order
1      Order_Date  datetime64[ns]      Date when the order was placed
2     Customer_ID          object   Unique identifier of the customer
3   Customer_Name          object                Name of the customer
4             Age         float64                 Age of the customer
5          Gender          object              Gender of the customer
6            City          object  City where the customer is located
7         Product          object       Name of the purchased product
8        Category          object   Category of the purchased product
9        Quantity           int64           Number of units purchased
10     Unit_Price         float64                      Price per unit
11    Total_Sales         float64    Total sales amount for the order

In [71]:
data_dictionary.to_excel("data_dictionary.xlsx", index=False)

print("Data dictionary saved successfully!")

Data dictionary saved successfully!

In [72]:
print("Shape:", df.shape)
print("\nMissing values:", df.isnull().sum().sum())
print("\nDuplicate rows:", df.duplicated().sum())
print("\nColumns:")
print(df.columns.tolist())

Shape: (1000, 12)

Missing values: 0

Duplicate rows: 0

Columns:
['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age', 'Gender', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price', 'Total_Sales']